// <auto-generated />
using System;
using AspNetCoreMvcModalForm.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspNetCoreMvcModalForm.Data.Migrations
{
    [DbContext(typeof(DataDbContext))]
    partial class DataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspNetCoreMvcModalForm.Business.Models.Solicitacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<Guid>("TipoSolicitacaoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("TipoSolicitacaoId");

                    b.ToTable("Solicitacao", (string)null);
                });

            modelBuilder.Entity("AspNetCoreMvcModalForm.Business.Models.TipoSolicitacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoSolicitacao", (string)null);
                });

            modelBuilder.Entity("AspNetCoreMvcModalForm.Business.Models.Solicitacao", b =>
                {
                    b.HasOne("AspNetCoreMvcModalForm.Business.Models.TipoSolicitacao", "TipoSolicitacao")
                        .WithMany()
                        .HasForeignKey("TipoSolicitacaoId")
                        .IsRequired();

                    b.Navigation("TipoSolicitacao");
                });
#pragma warning restore 612, 618
        }
    }
}
